### ISSUE TITLE
Empty string will be saved as "0" in database

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_numeric#13]
Empty string will be saved as "0" in database

see https://github.com/MetaModels/attribute_decimal/issues/13
and https://github.com/MetaModels/core/issues/1232

**Comment by discordier** [comment]
Moving to 2.1 as the related tickets are assigned to that milestone.

**Comment by zonky2** [comment]
@discordier we moved to MM 2.1.x or MM 3 ?

**Comment by discordier** [comment]
Reassigning to 2.1.1 as it affects the strict mode.

**Comment by MiniModel** [comment]
This issue has been labeled with testing but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@zonky2 could you please have a final look at this and tell if your issue has been resolved?

**Comment by zonky2** [comment]
@discordier works fine
