### ISSUE TITLE
"Eindeutige Werte" funktioniert nicht

### ISSUE THREAD

**Issue by KlausGrenoble** [MetaModels/attribute_numeric#5]
"Eindeutige Werte" funktioniert nicht.Man kann mehrmals den selben numerischen Wert wählen.
contao 3.4.5 und tng von heute (28.5.2015)
https://community.contao.org/de/showthread.php?57332-Eindeutige-Werte-unter-Contao3-4-5-und-MM-tng

**Comment by xantippe** [comment]
für die Validierung gehört neben https://github.com/MetaModels/core/issues/942 auch noch ein Update von https://github.com/MetaModels/attribute_numeric/blob/master/src/MetaModels/Attribute/Numeric/Numeric.php#L45-L55

```diff
    public function getAttributeSettingNames()
    {
        return array_merge(
            parent::getAttributeSettingNames(),
            array(
+                'isunique',
                'mandatory',
                'filterable',
                'searchable',
            )
        );
    }
```

einen PR mache ich (demnächst - sofern mir keiner zuvor kommt)

**Comment by xantippe** [comment]
PR gemacht https://github.com/MetaModels/attribute_numeric/pull/7

**Comment by xantippe** [comment]
getestet mit 
* DCG dev-hotfix-unique (c1314371)
* num dev-hotfix-2.0.0-alpha3 (a88a05df)

o.k.!

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@KlausGrenoble could you please have a final look at this and tell if your issue has been resolved?
