### ISSUE TITLE
Eingabe speichert "0" statt NULL

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_numeric#8]
SQL-Standard-Wert ist aber NULL

siehe auch https://github.com/MetaModels/attribute_decimal/issues/11

![shot134](https://cloud.githubusercontent.com/assets/1045318/13365289/7e3c288e-dcd4-11e5-988b-4b65b4151df4.jpg)

**Comment by xantippe** [comment]
siehe https://github.com/MetaModels/attribute_decimal/issues/11#issuecomment-190570092

**Comment by zonky2** [comment]
fixed with https://github.com/MetaModels/attribute_numeric/issues/13
